version: '3'
services:
  openldap:
    image: osixia/openldap:1.4.0
    environment:
      LDAP_ORGANISATION: "MiOrganizacion"
      LDAP_DOMAIN: "miorganizacion.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
